//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermercadosLaPoderosa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id { get; set; }
        public string Contenido { get; set; }
        public string Fecha { get; set; }
        public string Usuario { get; set; }
        public int RecetaId { get; set; }
    
        public virtual Receta Receta { get; set; }
    }
}
